### ISSUE TITLE
Dot instead of comma in plant_sensor.js

### ISSUE THREAD

**Issue by mvdwetering** [stanvn/zigbee-plant-sensor#1]
When looking at the plant_sensor.js I noticed that there is a dot where a comma seems to be intended.

https://github.com/stanvn/zigbee-plant-sensor/blob/df00646a77a4af5ab2aabcd2155c2bd02a301a6f/zigbee2mqtt/plant_sensor.js#L24

**Comment by stanvn** [comment]
Thanks, I fixed it. Strange Zigbee2MQTT did not complain about it.
