### ISSUE TITLE
support for nrf52833

### ISSUE THREAD

**Issue by letshin** [stanvn/zigbee-plant-sensor#6]
Hi, is there a possibility of adding support for nrf52833 please? Or if you give me an outline of what needs to be done I can look into this.

Thanks.

**Comment by stanvn** [comment]
Hi, the footprint of the [Ebyte NRF52833 module](https://www.cdebyte.com/products/E73-2G4M08S1E) is the same as the [nRF52840 one](https://www.cdebyte.com/products/E73-2G4M08S1C), so on the hardware side there is no need for any change. I do not expect that any changes needs to be done on the software to make it work with the nRF52833, however I have not tested this.

The main difference between the two is the amount of flash they have. You have to keep in mind that features like firmware update of the air, which I plan to implement, will not fit on the 512kB of the nRF52833.

**Comment by Hedda** [comment]
> The main difference between the two is the amount of flash they have. You have to keep in mind that features like firmware update of the air, which I plan to implement, will not fit on the 512kB of the nRF52833.

Another possible use-case example where nRF52833 512kB flash might be too small if in the distant future ever want to make a multi-protocol firmware image that would is compatible with Zigbee, Thread/Matter (OpenThread), and Bluetooth Low Evergy BLE.

Multiprotocol device firmware is likely to become more popular in the future with the use case being that the end-user buys/builds one single device and uses one common shared firmware image but when then uses it during the initial commissioning which protocol he/she wants to use. 

https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.thread_zigbee.v1.0.0%2Fthread_multiprotocol.html

E.i. nRF SoC can use several radio protocols, but only one at a time.

https://infocenter.nordicsemi.com/index.jsp?topic=%2Fsdk_tz_v4.0.0%2Fble_154_multiprotocol.html

So not concurrent multi-protocol using several protocols at the same time but instead having one firmware image that supports all but only one protocol is used by the user unless he/she factory reset it to be able to select a different protocol instead.

**Comment by stanvn** [comment]
I agree, Matter/Thread will most likely not fit on the nRF52833. This means I will not use the nRF52833 myself, but feel free to solder one yourself. My own hardware will use the nRF52840 for those reasons.

**Comment by letshin** [comment]
Fair. The b-parasite firmware has an option required for building for nrf52833 (which I am using as the nrf528400 was not available at JLCPCB) which is why I checked to see if it was possible out of the box as I know the pins are similar. I'll try this at some point in the near future and update here.

**Comment by stanvn** [comment]
I'll close this issue due to inactivity. Feel free to reopen it when you have new info
